name: Catalog Service

on:
  push:
    paths:
      - 'catalog-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: ./catalog-service
    defaults:
      run:
        working-directory: ${{ env.workdir }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw -ntp verify